// get list of all currencies
GET http://localhost:8080/currencies

###

// get currency by code
GET http://localhost:8080/currency/USD

###

// add currency
POST http://localhost:8080/currencies?code=BAM&fullName=Convertible Mark&sign=KM

###

// get exchange rates
GET http://localhost:8080/exchangeRates

###

// get exchange rate by code
GET http://localhost:8080/exchangeRate/AUDEUR

###

// add new exchange rate
POST http://localhost:8080/exchangeRates?baseCurrencyCode=BZD&targetCurrencyCode=EUR&rate=2.36

###

// change exchange rate
PATCH http://localhost:8080/exchangeRate/AUDBZD?rate=2.2

###

// currency exchange
GET http://localhost:8080/exchange?from=EUR&to=BYN&amount=10